function errorHandler(){alert('mozfullscreenerror')}
document.documentElement.addEventListener('mozfullscreenerror',errorHandler,!1);function toggleFullScreen(){if(!document.fullscreenElement&&!document.mozFullScreenElement&&!document.webkitFullscreenElement){if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen()}else if(document.documentElement.mozRequestFullScreen){document.documentElement.mozRequestFullScreen()}else if(document.documentElement.webkitRequestFullscreen){document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}}else{if(document.cancelFullScreen){document.cancelFullScreen()}else if(document.mozCancelFullScreen){document.mozCancelFullScreen()}else if(document.webkitCancelFullScreen){document.webkitCancelFullScreen()}}}
document.addEventListener('keydown',function(e){if(e.keyCode==13||e.keyCode==70){toggleFullScreen();$('.z-full-screen').toggleClass('active')}},!1);function RND(min,max){return Math.round(min-0.5+Math.random()*(max-min+1))}
function isArray(obj){if(obj.splice)return!0;else return!1}
function isInArray(el,arr){for(k in arr){if(el==arr[k])return!0}
    return!1}
function shakeArray(arr){arr.sort(function(){return Math.random()-0.5})}
function getBrowser(){var ua=navigator.userAgent;var bName=function(){if(ua.search(/Edge/)>-1)return"edge";if(ua.search(/MSIE/)>-1)return"ie";if(ua.search(/Trident/)>-1)return"ie11";if(ua.search(/Firefox/)>-1)return"firefox";if(ua.search(/Opera/)>-1)return"opera";if(ua.search(/OPR/)>-1)return"operaWebkit";if(ua.search(/YaBrowser/)>-1)return"yabrowser";if(ua.search(/Chrome/)>-1)return"chrome";if(ua.search(/Safari/)>-1)return"safari";if(ua.search(/Maxthon/)>-1)return"maxthon"}();var version;switch(bName){case "edge":version=(ua.split("Edge")[1]).split("/")[1];break;case "ie":version=(ua.split("MSIE ")[1]).split(";")[0];break;case "ie11":bName="ie";version=(ua.split("; rv:")[1]).split(")")[0];break;case "firefox":version=ua.split("Firefox/")[1];break;case "opera":version=ua.split("Version/")[1];break;case "operaWebkit":bName="opera";version=ua.split("OPR/")[1];break;case "yabrowser":version=(ua.split("YaBrowser/")[1]).split(" ")[0];break;case "chrome":version=(ua.split("Chrome/")[1]).split(" ")[0];break;case "safari":version=(ua.split("Version/")[1]).split(" ")[0];break;case "maxthon":version=ua.split("Maxthon/")[1];break}
    var platform='desktop';if(/iphone|ipad|ipod|android|blackberry|mini|windows\sce|palm/i.test(navigator.userAgent.toLowerCase()))platform='mobile';if(/iphone|ipad|ipod/i.test(navigator.userAgent.toLowerCase()))platform+=' os-ios';if(/android/i.test(navigator.userAgent.toLowerCase()))platform+=' os-android';var browsrObj;try{browsrObj={platform:platform,browser:bName,versionFull:version,versionShort:version.split(".")[0]}}catch(err){browsrObj={platform:platform,browser:'unknown',versionFull:'unknown',versionShort:'unknown'}}
    return browsrObj}
function isVisible(elem){var windowSTop=$(window).scrollTop();var coords=elem.offset();var windowHeight=document.documentElement.clientHeight;var topVisible=coords.top-windowHeight-windowSTop<0;return topVisible}
function findVisibleBoxes(){$('.animated').not('.on').each(function(){if(isVisible($(this))){$(this).addClass('on')}})}
function showVisible(){var s=$('img[realsrc]').each(function(){if(isVisible(this)){var r=$(this).attr('realsrc');$(this).attr('src',r)}})}